CREATE TABLE IF NOT EXISTS `icho_billing_invoices` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `invoice_type` ENUM('personal', 'job') NOT NULL DEFAULT 'personal',
    `issuer_citizenid` VARCHAR(50) NOT NULL,
    `issuer_name` VARCHAR(100) NOT NULL,
    `issuer_job_name` VARCHAR(50) DEFAULT NULL,
    `issuer_job_label` VARCHAR(100) DEFAULT NULL,
    `recipient_citizenid` VARCHAR(50) NOT NULL,
    `recipient_name` VARCHAR(100) NOT NULL,
    `amount` INT UNSIGNED NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    `job_pool_account` VARCHAR(50) DEFAULT NULL,
    `job_pool_percent` TINYINT UNSIGNED DEFAULT NULL,
    `job_pool_amount` INT UNSIGNED DEFAULT NULL,
    `job_remainder_amount` INT UNSIGNED DEFAULT NULL,
    `status` ENUM('unpaid', 'paid', 'cancelled') NOT NULL DEFAULT 'unpaid',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `paid_at` TIMESTAMP NULL DEFAULT NULL,
    `paid_by_account` VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_recipient_status` (`recipient_citizenid`, `status`),
    KEY `idx_issuer_status` (`issuer_citizenid`, `status`),
    KEY `idx_type_status` (`invoice_type`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
